name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World, again!"
      - name: Print goodbye
        run: echo "Done - bye (again)!"
